### ISSUE TITLE
Not an actual issue - THANK YOU!

### ISSUE THREAD

**Issue by loryanstrant** [C-Lock/desk_control#1]
I've got the same desk and controller but from a different company as I'm in Australia. It's obviously so crappy they no longer offer the BLE module.
I've searched for solutions before and even contacted the manufacturer, but never really got anything.
Today by random fluke I came upon your repo, and wanted to say thank you for creating this!

I intend to run this on my Raspberry Pi connected to the UPS under my desk, and will then have to figure out how to get it to talk to Home Assistant (as I plan to have my desk go up every time I get on a Teams call).

Thank you!

**Comment by C-Lock** [comment]
Glad the code has found it's way to be usefull in the wild! It's a bit rough around the edges, but it's worked without fail for the few commands I set up. 

If you end up figuring out any additional commands it can run (saving a height preset, for example), be sure to let me know. That would definitely make the script even more useful. 

I'd imagine you could probably figure a way to get Teams to trigger a custom script when a call comes in, that would be cool.

**Comment by loryanstrant** [comment]
The Teams bit I've mastered already: https://www.loryanstrant.com/2022/03/04/microsoft-teams-home-assistant-graph-take-your-presence-to-the-next-level/
So, all I need to do with your solution is:

1. figure out which bits need to be modified for my desk (am guessing UUID - just not sure where in the code I need to look)
2. how to surface it to Home Assistant to trigger those commands

Any chance you can give me some pointers for task #1?

Thanks again

**Comment by C-Lock** [comment]
Line 10 for the .sh,
Line 63 for the .py

You'll need the bluetueth address, it looks similar to a Mac address.
You can get this by scanning Bluetooth before and after powering on your device 

If your Bluetooth module has a qr code on the side, that qr code is the bluetueth address, if I recall correctly.

**Comment by loryanstrant** [comment]
You beautiful person, thank you so much!!!
After those two modifications, it worked straight away using my saved sit/stand heights.
Any interest in going further with this and exposing it so it can be triggered by Home Assistant? :-)

**Comment by loryanstrant** [comment]
Managed to get it working, by following this blog post: https://siytek.com/home-assistant-shell/
Will do a blog post about it in the next day or so and give you credit, as this has made my day!

**Comment by C-Lock** [comment]
Great! I'm looking forward to seeing the code and setting that up with the home assistant!

**Comment by loryanstrant** [comment]
Here's the blog post: https://www.loryanstrant.com/2022/04/25/automatically-raise-your-desk-when-joining-a-microsoft-teams-call-or-meeting/
